version: "3.4"

services:

  robot:
    container_name: robot
    restart: unless-stopped
    build:
      context: ./robot
      dockerfile: Dockerfile
    volumes:
      - ./resources:/resources:rw
    environment:
      PYTHONUNBUFFERED: 1

  selenium:
    container_name: selenium
    restart: unless-stopped
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444

  databse:
    container_name: database
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
