services:

  robot:
    container_name: robot
    restart: unless-stopped
    build:
      context: ./robot
      dockerfile: Dockerfile
    volumes:
      - ./resources:/resources:rw
    environment:
      PYTHONUNBUFFERED: 1

  database:
    container_name: database
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
